"use client";
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowRight,Check,Coffee,MousePointer2,Music2,Pause,Play,RotateCcw,Search,Sparkles,Type,X} from 'lucide-react';
import {closeGameTab,createRound,nextOpenTab,pauseRound,resumeRound,type PauseReason,type TabRound} from './tab-game-state';
const titles=['An article about attention','Fonts — final, final','Best dosa near me','The future of everything','Untitled presentation (9)','A reference for a reference','Why am I so distracted?','A very long interview','One more trend report','Weekend plans, allegedly','A thread about that thread','Something I will read later','Is this actually a trend?','Another take on taste','The perfect opening line','How to focus (12 tips)','That one very good ad','A book I meant to buy','Notes on my notes','The Bangalore weather','A tab playing music','Someone’s 2027 predictions','Research for the research','How to close all tabs'];
const favicons=[Search,Type,Coffee,Sparkles,Type,MousePointer2,Search,Music2];
const format=(ms:number)=>(ms/1000).toFixed(2);
function Stopwatch({round}:{round:TabRound}){
 const [value,setValue]=useState(round.elapsed);
 useEffect(()=>{const update=()=>setValue(round.elapsed+(round.phase==='running'?performance.now()-round.started:0));update();if(round.phase!=='running')return;const timer=setInterval(update,50);return()=>clearInterval(timer)},[round.phase,round.elapsed,round.started]);
 return <span className="game-time">{format(value)}<small>s</small></span>;
}
function TabFace({id}:{id:number}){const Icon=favicons[id%favicons.length];return <><span className="game-tab-top"><Icon size={17}/><span>{String(id+1).padStart(2,'0')}</span><X size={17}/></span><span className="game-tab-title">{titles[id]}</span></>}

export function MiniGame({active=true}:{active?:boolean}){
 const [round,setRound]=useState(()=>createRound());const current=useRef(round);
 const [runId,setRunId]=useState(0);const [records,setRecords]=useState<Record<string,number>>({});const recordRef=useRef(records);
 const [storageAvailable,setStorageAvailable]=useState(true);const [newBest,setNewBest]=useState(false);const [improvement,setImprovement]=useState<number|null>(null);
 const board=useRef<HTMLDivElement>(null);const overlay=useRef<HTMLDivElement>(null);const resultHeading=useRef<HTMLHeadingElement>(null);const resumeButton=useRef<HTMLButtonElement>(null);const focusFrame=useRef(0);const lastClosed=useRef(-1);
 const commit=useCallback((next:TabRound)=>{current.current=next;setRound(next)},[]);
 useEffect(()=>{try{const stored=localStorage.getItem('varun-tab-race-v2');let raw:Record<string,unknown>={};try{raw=JSON.parse(stored||'{}')}catch{}const valid:Record<string,number>={};for(const n of [12,24])if(typeof raw?.[n]==='number'&&Number.isFinite(raw[n])&&raw[n]>0)valid[n]=raw[n];recordRef.current=valid;setRecords(valid)}catch{setStorageAvailable(false)}return()=>cancelAnimationFrame(focusFrame.current)},[]);
 const pause=useCallback((reason:PauseReason='manual')=>{commit(pauseRound(current.current,performance.now(),reason))},[commit]);
 useEffect(()=>{if(!active){cancelAnimationFrame(focusFrame.current);pause('away')}},[active,pause]);
 useEffect(()=>{const hide=()=>{if(document.hidden)pause('hidden')};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[pause]);
 useEffect(()=>{if(!active||!['paused','finished'].includes(round.phase))return;const frame=requestAnimationFrame(()=>{overlay.current?.scrollIntoView({block:'center',behavior:'instant'});if(round.phase==='finished')resultHeading.current?.focus({preventScroll:true});else resumeButton.current?.focus({preventScroll:true})});return()=>cancelAnimationFrame(frame)},[round.phase,active]);
 const focusNext=(after=-1)=>{cancelAnimationFrame(focusFrame.current);focusFrame.current=requestAnimationFrame(()=>{const id=nextOpenTab(current.current,after);const b=board.current?.querySelector<HTMLButtonElement>(`[data-tab-id="${id}"]`);b?.focus({preventScroll:true});b?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'})})};
 const reset=(total=round.total,armed=false)=>{cancelAnimationFrame(focusFrame.current);lastClosed.current=-1;setRunId(id=>id+1);setNewBest(false);setImprovement(null);commit(createRound(total,armed?'armed':'ready'))};
 const start=()=>{reset(round.total,true);focusNext()};
 const resume=()=>{commit(resumeRound(current.current,performance.now()));focusNext(lastClosed.current)};
 const close=(id:number,keyboard:boolean)=>{const before=current.current;const next=closeGameTab(before,id,performance.now());if(next===before)return;lastClosed.current=id;commit(next);if(next.phase==='finished'){const best=recordRef.current[next.total];if(!next.practice&&(!best||next.elapsed<best)){setImprovement(best?best-next.elapsed:null);setNewBest(true);const updated={...recordRef.current,[next.total]:next.elapsed};recordRef.current=updated;setRecords(updated);try{localStorage.setItem('varun-tab-race-v2',JSON.stringify(updated))}catch{setStorageAvailable(false)}}}else if(keyboard)focusNext(id);else board.current?.focus({preventScroll:true})};
 const remaining=round.total-round.closed.length,percent=round.closed.length/round.total*100,playable=round.phase==='armed'||round.phase==='running';
 const status=round.phase==='armed'?'Your first close starts the clock.':round.phase==='running'?(remaining===1?'One last rabbit hole.':percent>=75?'Room to think.':percent>=50?'Halfway to a clear head.':percent>=25?'You weren’t going to read it.':'A little less on your mind.'):round.phase==='paused'?(round.pauseReason==='manual'?'Paused. Your progress is saved for this round.':'Paused while you were away. Your tabs are still here.'):round.phase==='finished'?'All closed. Nothing lost. Probably.':'A small exercise in letting go.';
 return <div className="tab-game" onKeyDown={e=>{if(e.key==='Escape'&&round.phase==='running'){e.preventDefault();pause()}}}>
  <div className="game-intro"><div><span className="meta">The occupational hazard of curiosity</span><h3>Tab bankruptcy.</h3></div><p>All those things you’ll read later.<br/>Close every tab. Beat your own time.</p></div>
  <div className={`game-browser game-${round.phase}`} ref={board} tabIndex={-1} data-total={round.total}>
   <div className="game-toolbar"><span className="game-window-controls" aria-hidden="true"><i/><i/><i/></span><span>too-many-tabs.browser</span><span className="game-window-note">A fresh start, in miniature.</span></div>
   <div className="game-setup"><div className="game-modes" role="group" aria-label="Number of tabs">{[12,24].map(n=><button key={n} aria-pressed={round.total===n} disabled={round.phase==='running'||round.phase==='paused'} onClick={()=>reset(n)}>{n} tabs<span>{n===12?'A quick clear':'Deep in it'}</span></button>)}</div><span className="game-personal-best">{storageAvailable?'Personal best':'Session best'}<strong>{records[round.total]?`${format(records[round.total])}s`:'Yours to set'}</strong></span></div>
   <div className="game-hud"><div className="game-remaining"><span>Tabs left</span><strong key={`${runId}-${remaining}`}>{String(remaining).padStart(2,'0')}<small>/ {round.total}</small></strong></div><div className="game-clock"><span>{round.practice?'Practice time':'Time'}</span><Stopwatch round={round}/></div><div className="game-controls">{round.phase==='running'&&<button onClick={()=>pause()} aria-label="Pause game"><Pause size={18}/><span>Pause</span></button>}{round.phase==='paused'&&<button onClick={resume} aria-label="Resume game"><Play size={18}/><span>Resume</span></button>}{['armed','running','paused'].includes(round.phase)&&<button onClick={start} aria-label="Restart game"><RotateCcw size={18}/><span>Restart</span></button>}</div></div>
   <div className="game-progress" role="progressbar" aria-label="Tabs cleared" aria-valuemin={0} aria-valuemax={round.total} aria-valuenow={round.closed.length}><span style={{transform:`scaleX(${percent/100})`}}/></div>
   <div className="game-status"><p id="tab-game-instruction">{status}</p><span>{round.closed.length} cleared<Check size={14}/></span></div>
   <span className="sr-only" role="status" aria-live="polite">{active&&round.phase!=='finished'?status:''}</span>
   <div className="game-stage"><div className="game-grid" role="group" aria-label="Open tabs" aria-describedby="tab-game-instruction" key={runId}>{Array.from({length:round.total},(_,id)=>{const cleared=round.closed.includes(id);return <div key={id} className={`game-slot ${cleared?'is-cleared':''}`}>
    {cleared?<><span className="game-tab game-ghost" aria-hidden="true"><TabFace id={id}/></span><span className="game-cleared" aria-hidden="true"><Check size={22}/><span>Let it go.</span></span></>:<button className="game-tab" data-tab-id={id} disabled={!playable} onClick={e=>close(id,e.detail===0)} onKeyDown={e=>{if(e.repeat&&['Enter',' '].includes(e.key))e.preventDefault()}} aria-label={`Close tab ${id+1}: ${titles[id]}`}><TabFace id={id}/></button>}
   </div>})}</div>
   {['ready','paused','finished'].includes(round.phase)&&<div className={`game-overlay ${round.phase==='finished'?'is-result':''}`}><div className="game-overlay-panel" ref={overlay}>
    {round.phase==='ready'&&<><span className="game-round-label">{round.total} open tabs. All “essential”.</span><h4>Close tabs.<br/><em>Find peace.</em></h4><button className="game-primary" onClick={start}>Clear my head<ArrowRight size={20}/></button><p>Click anywhere on a tab to close it.<br/>The first close starts the clock.</p><small>Pausing keeps your progress and makes it a practice round.</small></>}
    {round.phase==='paused'&&<><Pause className="game-pause-icon" size={26}/><h4>A little breather.</h4><p>{round.pauseReason==='manual'?'Pick up where you left off.':'We stopped the clock while you were away.'}<br/>Paused rounds are practice rounds.</p><button className="game-primary" ref={resumeButton} onClick={resume}>Keep going<Play size={18}/></button></>}
    {round.phase==='finished'&&<><span className="game-round-label">{round.practice?'Practice round complete':newBest?'A new personal best':'All tabs closed'}</span><h4 ref={resultHeading} tabIndex={-1} aria-label={`${round.practice?'Practice round. ':''}All ${round.total} tabs closed in ${format(round.elapsed)} seconds${newBest?'. A new personal best.':''}`}>Clear head.</h4><strong className="game-result-time">{format(round.elapsed)}<small>s</small></strong><p>{improvement?`${format(improvement)} seconds faster than your best.`:`${round.total} tabs. A little more room to think.`}</p><button className="game-primary" onClick={start}>One more round<RotateCcw size={18}/></button><div className="game-confetti" aria-hidden="true">{Array.from({length:8},(_,i)=><i key={i} style={{'--piece':i} as CSSProperties}/>)}</div></>}
   </div></div>}
   </div>
   <div className="game-bottom"><span>Enter or Space closes a focused tab. Focus moves to the next one. Esc pauses.</span><span>Your real tabs are safe. {storageAvailable?'Best times stay on this device.':'Best times last for this visit.'}</span></div>
  </div>
 </div>;
}
