export const notes = [
  {
    id: "arriving", number: "01", label: "Arriving alone", category: "Belonging", title: "A table for one, a page to doodle on.",
    teaser: "At Papa’s, a solo guest can pick up a page without having to join a conversation.",
    paragraphs: ["“Table for one” tells a host how many places to set. It says less about how much company a person might want. Someone could be there for privacy, open to a conversation, or waiting to see how the evening feels. The number on the booking is a poor substitute for understanding that difference.", "At Papa’s, a 12-seat restaurant in Mumbai, Touching Grass describes reading material guests can colour and doodle in. I like the small permission that offers: someone arriving alone can get absorbed in a page, look up, say something, or keep drawing. The page doesn’t demand a particular kind of evening.", "I would be wary of turning that into an instruction to make everyone social. A good experience should be able to accommodate curiosity, shyness and the wish to be left alone. Sometimes those are three stages of the same evening. The design question is how to make contact possible without making participation the price of being there."],
    question: "How could an experience feel complete for one person while making connection possible without making it compulsory?",
    evidence: "Touching Grass describes Papa’s reading material on printed pp. 62–63 and discusses solo participation in Solo-Sure. This interpretation does not establish a measured effect on loneliness.",
    sources: [{ title: "Touching Grass · Papa’s · pp. 62–63", url: "/assets/touching-grass-2026.pdf#page=31" }, { title: "Touching Grass · Solo-Sure · pp. 74–79", url: "/assets/touching-grass-2026.pdf#page=37" }]
  },
  {
    id: "friction", number: "02", label: "One more purchase", category: "Consumption", title: "At checkout, I hesitate.",
    teaser: "If I hesitate at checkout, is the price unclear, or have I changed my mind?",
    paragraphs: ["A checkout that takes fewer steps can be excellent design. The next question is which decision we have made easier. In Consumed, the discussion of convenience sits alongside impulsive buying, bundled deliveries and opportunities to pause. There is a tension here worth staying with.", "A moment of hesitation can be useful information. Perhaps the price is unclear. Perhaps the person has remembered they already own something similar. Those call for different responses. I’d want a product team to be able to explain which hesitation it is removing, rather than treating every pause as a defect. There’s a meaningful difference between helping someone finish what they came to do and making it harder to notice that they’ve changed their mind."],
    question: "What does this convenience help someone do—and what does it make easier to overlook?",
    evidence: "Consumed discusses convenience, impulse and more considered forms of consumption on printed pp. 20, 23 and 25. The strategic question is a further interpretation of those tensions.",
    sources: [{ title: "Consumed · Convenience and consumption · pp. 20–25", url: "/assets/consumed-2024.pdf#page=22" }]
  },
  {
    id: "meme", number: "03", label: "A forwarded meme", category: "Media", title: "This reminded me of you.",
    teaser: "A forwarded image may mean little to a stranger and a lot to the person who gets the joke.",
    paragraphs: ["A meme arrives with no explanation. The person who sent it knows you will understand: a conversation you had, a habit you share, an old irritation that has somehow become funny. Someone else could look at exactly the same image and see very little. Part of its meaning exists between two people, outside the frame.", "Ria and I discussed this in our conversation for Hannah Grey: memes as a way of maintaining relationships, expressing something difficult, or making room for dissent. That interests me because it changes what we are looking at. The image may be disposable; the act of choosing a particular person to receive it can carry care, familiarity or an invitation to respond.", "This complicates what I mean by fighting content pollution. I do not want a cultural environment in which everything has to demonstrate seriousness. Absurdity is useful. So is an exchange that requires very little effort on a day when a proper conversation feels impossible. Something can look slight and still be exact about what it is doing.", "It also makes “shareable” a less complete ambition than it sounds. A brand can make something people recognise, but it cannot prescribe the meaning people give it when they pass it on. They may use it affectionately, repurpose it, laugh at it, or make it part of a conversation the brand would never have imagined.", "I want to begin with that exchange: who might send this, to whom, and what would sending it let them say? It brings a person and a relationship back into a discussion that can otherwise become entirely about the performance of an asset."],
    question: "What might someone use this to say to another person?",
    evidence: "The interview discusses meme-sharing, everyday communication and cultural expression. This note develops those arguments into a question for brand communications.",
    sources: [{ title: "Breaking Western Narratives · pp. 27–28", url: "https://static1.squarespace.com/static/61e5c10ebb3de93bd4890f0c/t/67be0786e724152d6136f05d/1740507025325/Cultural%2BVibrations_%2BShifting%2BGround%2B2025.pdf#page=27" }]
  },
  {
    id: "global", number: "04", label: "A ‘global’ trend", category: "Perspective", title: "Who called it “global”?",
    teaser: "A Western observation can become a general rule; an Indian one can be filed as local.",
    paragraphs: ["In our conversation for Hannah Grey, Ria and I questioned an asymmetry in cultural analysis: a Western observation can travel as a global insight, while an Indian observation is more readily filed as local. The label matters. It decides which experience provides the explanation and which experience is expected to be explained by it.", "Take the idea that people are tired of the internet. For someone who has spent years being addressed, measured and recommended to, that may describe something important. Someone encountering new possibilities through the same technology may feel excitement instead. Both can be responding sensibly to their circumstances. If we begin with fatigue as the global condition, excitement becomes an exception to account for, or a phase that will eventually catch up.", "I am wary of that implied timeline. It can make one place’s present look like another place’s inevitable future. It also directs attention towards whatever resembles the existing explanation. A behaviour that would have complicated the argument may disappear before the research has really begun.", "Starting in India does not automatically solve this. “The Indian consumer” can conceal differences in language, access and experience just as efficiently. I want to know where an observation was made, who was able to enter the conversation, and which conditions made the behaviour intelligible there.", "A useful insight should be able to travel with that information still attached. Then the question becomes what holds elsewhere, what changes, and what we have misunderstood. There is more work in that approach. There is also more chance of encountering something we did not already have a name for."],
    question: "Whose experience does this explanation begin with, and what would change if we started somewhere else?",
    evidence: "Breaking Western Narratives, an interview with Ria Chopra and Varun, considers Western framing and different relationships with the internet. Access history as a strategic lens is developed here from that discussion.",
    sources: [{ title: "Breaking Western Narratives · pp. 24–25", url: "https://static1.squarespace.com/static/61e5c10ebb3de93bd4890f0c/t/67be0786e724152d6136f05d/1740507025325/Cultural%2BVibrations_%2BShifting%2BGround%2B2025.pdf#page=24" }]
  },
  {
    id: "access", number: "05", label: "A missed gig", category: "Taste", title: "The gig someone missed.",
    teaser: "A ticket price, a long journey, an evening that doesn’t fit around work. Absence doesn’t always mean disinterest.",
    paragraphs: ["I like reading taste for what it reveals about a person’s world. I also want to know what their world makes available. The gig someone misses may have been too expensive, too far away or impossible to fit around work. Someone can care deeply about a scene without appearing in its attendance data.", "That complicates the flattering stories brands tell about their audiences: curious, discerning, culturally fluent. Those descriptions can quietly turn access into a personality trait. Before deciding that people need a more compelling invitation, I’d ask what it currently takes to accept one, and whose circumstances the experience assumes."],
    question: "Are we reading a lack of interest, or a difficulty taking part?",
    evidence: "This is a further question prompted by Touching Grass’s discussion of identity and experience. The US National Endowment for the Arts’ attendance research provides a broader analytical precedent on cost, time and access; it is not evidence of current Indian prevalence.",
    sources: [{ title: "Touching Grass · Identity and experience · pp. 8–11", url: "/assets/touching-grass-2026.pdf#page=4" }, { title: "NEA · When Going Gets Tough · Attendance barriers", url: "https://www.arts.gov/sites/default/files/when-going-gets-tough-revised2.pdf" }]
  },
  {
    id: "names", number: "06", label: "A trend name", category: "Cultural strategy", title: "A neat name on a slide.",
    teaser: "A neat name can make a small example look like a settled change.",
    paragraphs: ["I enjoy finding language for something people recognise but haven’t quite articulated. There’s a risk in getting too pleased with the name, though. Once a behaviour becomes a neat slide, it becomes easier to circulate and harder to see in all its awkward detail.", "Who does the description fit? Where does it stop fitting? What would make me revise it? I want those questions to survive the presentation. The closing pages of Touching Grass acknowledge the compression involved in naming culture. For me, that is part of the discipline: following an observation far enough to make a decision more considered, while staying honest about the distance between an interesting example and a change that is widely shared."],
    question: "What would we need to see before making this observation the basis of a decision?",
    evidence: "Touching Grass’s closing reflection discusses the limits of labels, selective observation and cultural overproduction. This is a new statement of a question already present in the report.",
    sources: [{ title: "Touching Grass · Closing reflection · pp. 130–131", url: "/assets/touching-grass-2026.pdf#page=65" }]
  }
];
